# 网页模糊抓取
- type: webfuzz
  options:
    url: https://my.ishadowx.biz
    
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://io.freess.info

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://view.freev2ray.org/
    
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://raw.fastgit.org/luyuliang1234/Free-v2ray-link-vmess/master/README.md
    
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://raw.fastgit.org/Nadenesmith1221/freev2ray/main/README.md

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://www.sshagan.net/?page=v2ray
   
# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/learnhard-cn/free_proxy_ss/main/free
   
# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/xiyaowong/freeFQ/main/v2ray
       
# 订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/oslook/clash-freenode/main/clash.yaml
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/freefq/free/master/v2
    
# 订阅链接
- type: subscribe
  options:
    url: https://jiang.netlify.app
    
# clash
- type: clash
  options:
    url: https://suo.yt/8H8wpFu
    
# clash
- type: clash
  options:
    url: https://git.io/emzclash
    
# 订阅链接
- type: subscribe
  options:
    url: https://git.io/emzv2ray
    
# 订阅链接
- type: subscribe
  options:
    url: https://v2ray.banyunxiaoxi.ml

# 订阅链接
- type: subscribe
  options:
    url: https://youlianboshi.netlify.app

# 订阅链接
- type: subscribe
  options:
    url: https://gooii.ml/v2ray/sub

# 订阅链接
- type: clash
  options:
    url: https://proxypoolss.tk/clash/proxies?speed=20

# 订阅链接
- type: clash
  options:
    url: https://proxy.yugogo.xyz/clash/config

# 订阅链接
- type: clash
  options:
    url: https://www.233660.xyz/clash/config

# 订阅链接
- type: subscribe
  options:
    url: https://v1.mk/dcE0fSH

# 订阅链接
- type: subscribe
  options:
    url: https://v1.mk/xsCuC1p
# 订阅链接
- type: subscribe
  options:
    url: https://v1.mk/DW2ZUwc

# 订阅链接
- type: subscribe
  options:
    url: https://v1.mk/yEYSs0w

# 订阅链接
- type: clash
  options:
    url: https://v1.mk/xhzvCJo

# 订阅链接
- type: clash
  options:
    url: https://v1.mk/ZKTr9q6

# 订阅链接
- type: clash
  options:
    url: https://free.kingfu.cf/clash/config

# 订阅链接
- type: clash
  options:
    url: https://emby.luoml.eu.org/clash/config

# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/adiwzx/freenode/main/adispeed.txt

# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/umelabs/node.umelabs.dev/master/Subscribe/v2ray.md

# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/freefq/free/master/v2

# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/adiwzx/freenode/main/adispeed.txt

# 订阅链接
- type: clash
  options:
    url: https://free.mengbai.cf/clash/config

# 订阅链接
- type: clash
  options:
    url: https://free.dswang.ga/clash/config

# 订阅链接
- type: clash
  options:
    url: https://sspool.herokuapp.com/clash/config

# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/learnhard-cn/free_proxy_ss/main/free

# 订阅链接
- type: subscribe
  options:
    url: https://iwxf.netlify.app

# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/freefq/free/master/ssr
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/freefq/free/master/v2

# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/adiwzx/freenode/main/adispeed.txt
    
# 订阅链接
- type: subscribe
  options:
    url: https://hyt-allen-xu.netlify.app
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/jsnjsnwbtwbt/2D2F/main/2C2F
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/jsnjsnwbtwbt/TEzNC1jOTY1ZGE5OWM1ZT/main/Stable
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/coolapijust/cxkv2-/main/IPLC
    
# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/coolapijust/cxkv2-/main/README.md

# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/coolapijust/cxkv2-/main/SurfShark

# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/coolapijust/cxkv2-/main/plate

# 订阅链接
- type: subscribe
  options:
    url: https://aaxc.club/free-nodes.txt?lt=3

# 订阅链接
- type: subscribe
  options:
    url: https://sspool.herokuapp.com/clash/proxies

# 订阅链接
- type: subscribe
  options:
    url: https://caicai.moose.tk/vmess/sub

# tg频道抓取
- type: tgchannel
  options:
    channel: dangzhibu
    num: 200

# tg频道抓取
- type: tgchannel
  options:
    channel: baipiaov2
    num: 200

# tg频道抓取
- type: tgchannel
  options:
    channel: V2list
    num: 200

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrshares
    num: 200

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.fastgit.org/adiwzx/freenode/main/adispeed.yml

# 模糊抓取订阅链接——old
- type: webfuzzsub
  options:
    url: https://raw.fastgit.org/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/ssrsub/ssr/master/v2ray

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.fastgit.org/du5/free/master/file/0909/Clash.yaml

# 某个网站抓取
- type: web-freessrxyz
  options:
